<script setup>
import { ref, defineEmits } from 'vue';
import { supabase } from '../lib/supabaseClient';

const newComment = ref('');
const author = ref('');
const errorMessage = ref('');
const isSubmitting = ref(false);
const emit = defineEmits(['commentAdded']);

const postComment = async () => {
  if (!newComment.value.trim() || !author.value.trim()) {
    errorMessage.value = 'Please fill in all fields';
    return;
  }
  
  isSubmitting.value = true;
  errorMessage.value = '';

  try {
    const { data, error } = await supabase
      .from('comments')
      .insert([{ 
        content: newComment.value, 
        author: author.value,
        // Add created_at if it's not auto-generated by Supabase
        created_at: new Date().toISOString() 
      }])
      .select();

    if (error) {
      console.error('Error posting comment:', error);
      errorMessage.value = `Error: ${error.message}`;
    } else {
      newComment.value = '';
      author.value = '';
      emit('commentAdded', data[0]); // Pass the new comment data to parent
    }
  } catch (err) {
    console.error('Unexpected error:', err);
    errorMessage.value = 'An unexpected error occurred';
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<template>
  <form @submit.prevent="postComment" class="comment-form">
    <div v-if="errorMessage" class="error-message">{{ errorMessage }}</div>
    <input v-model="author" type="text" placeholder="Your Name" required />
    <textarea v-model="newComment" placeholder="Write a comment..." required></textarea>
    <button type="submit" :disabled="isSubmitting">
      {{ isSubmitting ? 'Posting...' : 'Post Comment' }}
    </button>
  </form>
</template>

<style scoped>
.comment-form {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-bottom: 20px;
}

.comment-form input,
.comment-form textarea {
  width: 100%;
  padding: 8px;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.comment-form button {
  background-color: #007bff;
  color: white;
  border: none;
  padding: 10px;
  cursor: pointer;
  border-radius: 5px;
}

.comment-form button:hover:not([disabled]) {
  background-color: #0056b3;
}

.comment-form button[disabled] {
  background-color: #cccccc;
  cursor: not-allowed;
}

.error-message {
  color: #dc3545;
  margin-bottom: 10px;
  padding: 8px;
  background-color: #f8d7da;
  border-radius: 5px;
}
</style>